// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/proto/ratchet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatchetDaemon_CreateSession_FullMethodName       = "/ratchet.RatchetDaemon/CreateSession"
	RatchetDaemon_ListSessions_FullMethodName        = "/ratchet.RatchetDaemon/ListSessions"
	RatchetDaemon_AttachSession_FullMethodName       = "/ratchet.RatchetDaemon/AttachSession"
	RatchetDaemon_DetachSession_FullMethodName       = "/ratchet.RatchetDaemon/DetachSession"
	RatchetDaemon_KillSession_FullMethodName         = "/ratchet.RatchetDaemon/KillSession"
	RatchetDaemon_SendMessage_FullMethodName         = "/ratchet.RatchetDaemon/SendMessage"
	RatchetDaemon_RespondToPermission_FullMethodName = "/ratchet.RatchetDaemon/RespondToPermission"
	RatchetDaemon_AddProvider_FullMethodName         = "/ratchet.RatchetDaemon/AddProvider"
	RatchetDaemon_ListProviders_FullMethodName       = "/ratchet.RatchetDaemon/ListProviders"
	RatchetDaemon_TestProvider_FullMethodName        = "/ratchet.RatchetDaemon/TestProvider"
	RatchetDaemon_RemoveProvider_FullMethodName      = "/ratchet.RatchetDaemon/RemoveProvider"
	RatchetDaemon_SetDefaultProvider_FullMethodName  = "/ratchet.RatchetDaemon/SetDefaultProvider"
	RatchetDaemon_ListAgents_FullMethodName          = "/ratchet.RatchetDaemon/ListAgents"
	RatchetDaemon_GetAgentStatus_FullMethodName      = "/ratchet.RatchetDaemon/GetAgentStatus"
	RatchetDaemon_StartTeam_FullMethodName           = "/ratchet.RatchetDaemon/StartTeam"
	RatchetDaemon_GetTeamStatus_FullMethodName       = "/ratchet.RatchetDaemon/GetTeamStatus"
	RatchetDaemon_ApprovePlan_FullMethodName         = "/ratchet.RatchetDaemon/ApprovePlan"
	RatchetDaemon_RejectPlan_FullMethodName          = "/ratchet.RatchetDaemon/RejectPlan"
	RatchetDaemon_Health_FullMethodName              = "/ratchet.RatchetDaemon/Health"
	RatchetDaemon_Shutdown_FullMethodName            = "/ratchet.RatchetDaemon/Shutdown"
)

// RatchetDaemonClient is the client API for RatchetDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatchetDaemonClient interface {
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error)
	AttachSession(ctx context.Context, in *AttachReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	DetachSession(ctx context.Context, in *DetachReq, opts ...grpc.CallOption) (*Empty, error)
	KillSession(ctx context.Context, in *KillReq, opts ...grpc.CallOption) (*Empty, error)
	// Chat
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// Permissions
	RespondToPermission(ctx context.Context, in *PermissionResponse, opts ...grpc.CallOption) (*Empty, error)
	// Providers
	AddProvider(ctx context.Context, in *AddProviderReq, opts ...grpc.CallOption) (*Provider, error)
	ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error)
	TestProvider(ctx context.Context, in *TestProviderReq, opts ...grpc.CallOption) (*TestProviderResult, error)
	RemoveProvider(ctx context.Context, in *RemoveProviderReq, opts ...grpc.CallOption) (*Empty, error)
	SetDefaultProvider(ctx context.Context, in *SetDefaultProviderReq, opts ...grpc.CallOption) (*Empty, error)
	// Agents
	ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentList, error)
	GetAgentStatus(ctx context.Context, in *AgentStatusReq, opts ...grpc.CallOption) (*Agent, error)
	// Teams
	StartTeam(ctx context.Context, in *StartTeamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TeamEvent], error)
	GetTeamStatus(ctx context.Context, in *TeamStatusReq, opts ...grpc.CallOption) (*TeamStatus, error)
	// Plan mode
	ApprovePlan(ctx context.Context, in *ApprovePlanReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	RejectPlan(ctx context.Context, in *RejectPlanReq, opts ...grpc.CallOption) (*Empty, error)
	// Daemon
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type ratchetDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewRatchetDaemonClient(cc grpc.ClientConnInterface) RatchetDaemonClient {
	return &ratchetDaemonClient{cc}
}

func (c *ratchetDaemonClient) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, RatchetDaemon_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionList)
	err := c.cc.Invoke(ctx, RatchetDaemon_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) AttachSession(ctx context.Context, in *AttachReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatchetDaemon_ServiceDesc.Streams[0], RatchetDaemon_AttachSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachReq, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_AttachSessionClient = grpc.ServerStreamingClient[ChatEvent]

func (c *ratchetDaemonClient) DetachSession(ctx context.Context, in *DetachReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_DetachSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) KillSession(ctx context.Context, in *KillReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_KillSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatchetDaemon_ServiceDesc.Streams[1], RatchetDaemon_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageReq, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_SendMessageClient = grpc.ServerStreamingClient[ChatEvent]

func (c *ratchetDaemonClient) RespondToPermission(ctx context.Context, in *PermissionResponse, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_RespondToPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) AddProvider(ctx context.Context, in *AddProviderReq, opts ...grpc.CallOption) (*Provider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provider)
	err := c.cc.Invoke(ctx, RatchetDaemon_AddProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderList)
	err := c.cc.Invoke(ctx, RatchetDaemon_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) TestProvider(ctx context.Context, in *TestProviderReq, opts ...grpc.CallOption) (*TestProviderResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestProviderResult)
	err := c.cc.Invoke(ctx, RatchetDaemon_TestProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) RemoveProvider(ctx context.Context, in *RemoveProviderReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_RemoveProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) SetDefaultProvider(ctx context.Context, in *SetDefaultProviderReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_SetDefaultProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) ListAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentList)
	err := c.cc.Invoke(ctx, RatchetDaemon_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) GetAgentStatus(ctx context.Context, in *AgentStatusReq, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, RatchetDaemon_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) StartTeam(ctx context.Context, in *StartTeamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TeamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatchetDaemon_ServiceDesc.Streams[2], RatchetDaemon_StartTeam_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartTeamReq, TeamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_StartTeamClient = grpc.ServerStreamingClient[TeamEvent]

func (c *ratchetDaemonClient) GetTeamStatus(ctx context.Context, in *TeamStatusReq, opts ...grpc.CallOption) (*TeamStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeamStatus)
	err := c.cc.Invoke(ctx, RatchetDaemon_GetTeamStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) ApprovePlan(ctx context.Context, in *ApprovePlanReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatchetDaemon_ServiceDesc.Streams[3], RatchetDaemon_ApprovePlan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApprovePlanReq, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_ApprovePlanClient = grpc.ServerStreamingClient[ChatEvent]

func (c *ratchetDaemonClient) RejectPlan(ctx context.Context, in *RejectPlanReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_RejectPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RatchetDaemon_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratchetDaemonClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RatchetDaemon_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatchetDaemonServer is the server API for RatchetDaemon service.
// All implementations must embed UnimplementedRatchetDaemonServer
// for forward compatibility.
type RatchetDaemonServer interface {
	// Session management
	CreateSession(context.Context, *CreateSessionReq) (*Session, error)
	ListSessions(context.Context, *Empty) (*SessionList, error)
	AttachSession(*AttachReq, grpc.ServerStreamingServer[ChatEvent]) error
	DetachSession(context.Context, *DetachReq) (*Empty, error)
	KillSession(context.Context, *KillReq) (*Empty, error)
	// Chat
	SendMessage(*SendMessageReq, grpc.ServerStreamingServer[ChatEvent]) error
	// Permissions
	RespondToPermission(context.Context, *PermissionResponse) (*Empty, error)
	// Providers
	AddProvider(context.Context, *AddProviderReq) (*Provider, error)
	ListProviders(context.Context, *Empty) (*ProviderList, error)
	TestProvider(context.Context, *TestProviderReq) (*TestProviderResult, error)
	RemoveProvider(context.Context, *RemoveProviderReq) (*Empty, error)
	SetDefaultProvider(context.Context, *SetDefaultProviderReq) (*Empty, error)
	// Agents
	ListAgents(context.Context, *Empty) (*AgentList, error)
	GetAgentStatus(context.Context, *AgentStatusReq) (*Agent, error)
	// Teams
	StartTeam(*StartTeamReq, grpc.ServerStreamingServer[TeamEvent]) error
	GetTeamStatus(context.Context, *TeamStatusReq) (*TeamStatus, error)
	// Plan mode
	ApprovePlan(*ApprovePlanReq, grpc.ServerStreamingServer[ChatEvent]) error
	RejectPlan(context.Context, *RejectPlanReq) (*Empty, error)
	// Daemon
	Health(context.Context, *Empty) (*HealthResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedRatchetDaemonServer()
}

// UnimplementedRatchetDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatchetDaemonServer struct{}

func (UnimplementedRatchetDaemonServer) CreateSession(context.Context, *CreateSessionReq) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedRatchetDaemonServer) ListSessions(context.Context, *Empty) (*SessionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRatchetDaemonServer) AttachSession(*AttachReq, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method AttachSession not implemented")
}
func (UnimplementedRatchetDaemonServer) DetachSession(context.Context, *DetachReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachSession not implemented")
}
func (UnimplementedRatchetDaemonServer) KillSession(context.Context, *KillReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedRatchetDaemonServer) SendMessage(*SendMessageReq, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRatchetDaemonServer) RespondToPermission(context.Context, *PermissionResponse) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToPermission not implemented")
}
func (UnimplementedRatchetDaemonServer) AddProvider(context.Context, *AddProviderReq) (*Provider, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProvider not implemented")
}
func (UnimplementedRatchetDaemonServer) ListProviders(context.Context, *Empty) (*ProviderList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedRatchetDaemonServer) TestProvider(context.Context, *TestProviderReq) (*TestProviderResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestProvider not implemented")
}
func (UnimplementedRatchetDaemonServer) RemoveProvider(context.Context, *RemoveProviderReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProvider not implemented")
}
func (UnimplementedRatchetDaemonServer) SetDefaultProvider(context.Context, *SetDefaultProviderReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultProvider not implemented")
}
func (UnimplementedRatchetDaemonServer) ListAgents(context.Context, *Empty) (*AgentList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedRatchetDaemonServer) GetAgentStatus(context.Context, *AgentStatusReq) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedRatchetDaemonServer) StartTeam(*StartTeamReq, grpc.ServerStreamingServer[TeamEvent]) error {
	return status.Error(codes.Unimplemented, "method StartTeam not implemented")
}
func (UnimplementedRatchetDaemonServer) GetTeamStatus(context.Context, *TeamStatusReq) (*TeamStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamStatus not implemented")
}
func (UnimplementedRatchetDaemonServer) ApprovePlan(*ApprovePlanReq, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method ApprovePlan not implemented")
}
func (UnimplementedRatchetDaemonServer) RejectPlan(context.Context, *RejectPlanReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectPlan not implemented")
}
func (UnimplementedRatchetDaemonServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRatchetDaemonServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedRatchetDaemonServer) mustEmbedUnimplementedRatchetDaemonServer() {}
func (UnimplementedRatchetDaemonServer) testEmbeddedByValue()                       {}

// UnsafeRatchetDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatchetDaemonServer will
// result in compilation errors.
type UnsafeRatchetDaemonServer interface {
	mustEmbedUnimplementedRatchetDaemonServer()
}

func RegisterRatchetDaemonServer(s grpc.ServiceRegistrar, srv RatchetDaemonServer) {
	// If the following call panics, it indicates UnimplementedRatchetDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatchetDaemon_ServiceDesc, srv)
}

func _RatchetDaemon_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).CreateSession(ctx, req.(*CreateSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).ListSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_AttachSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatchetDaemonServer).AttachSession(m, &grpc.GenericServerStream[AttachReq, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_AttachSessionServer = grpc.ServerStreamingServer[ChatEvent]

func _RatchetDaemon_DetachSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).DetachSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_DetachSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).DetachSession(ctx, req.(*DetachReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).KillSession(ctx, req.(*KillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatchetDaemonServer).SendMessage(m, &grpc.GenericServerStream[SendMessageReq, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_SendMessageServer = grpc.ServerStreamingServer[ChatEvent]

func _RatchetDaemon_RespondToPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).RespondToPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_RespondToPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).RespondToPermission(ctx, req.(*PermissionResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_AddProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).AddProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_AddProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).AddProvider(ctx, req.(*AddProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).ListProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_TestProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).TestProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_TestProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).TestProvider(ctx, req.(*TestProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_RemoveProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).RemoveProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_RemoveProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).RemoveProvider(ctx, req.(*RemoveProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_SetDefaultProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).SetDefaultProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_SetDefaultProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).SetDefaultProvider(ctx, req.(*SetDefaultProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).ListAgents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).GetAgentStatus(ctx, req.(*AgentStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_StartTeam_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartTeamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatchetDaemonServer).StartTeam(m, &grpc.GenericServerStream[StartTeamReq, TeamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_StartTeamServer = grpc.ServerStreamingServer[TeamEvent]

func _RatchetDaemon_GetTeamStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).GetTeamStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_GetTeamStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).GetTeamStatus(ctx, req.(*TeamStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_ApprovePlan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApprovePlanReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatchetDaemonServer).ApprovePlan(m, &grpc.GenericServerStream[ApprovePlanReq, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatchetDaemon_ApprovePlanServer = grpc.ServerStreamingServer[ChatEvent]

func _RatchetDaemon_RejectPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).RejectPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_RejectPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).RejectPlan(ctx, req.(*RejectPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatchetDaemon_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatchetDaemonServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatchetDaemon_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatchetDaemonServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RatchetDaemon_ServiceDesc is the grpc.ServiceDesc for RatchetDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatchetDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratchet.RatchetDaemon",
	HandlerType: (*RatchetDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _RatchetDaemon_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _RatchetDaemon_ListSessions_Handler,
		},
		{
			MethodName: "DetachSession",
			Handler:    _RatchetDaemon_DetachSession_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _RatchetDaemon_KillSession_Handler,
		},
		{
			MethodName: "RespondToPermission",
			Handler:    _RatchetDaemon_RespondToPermission_Handler,
		},
		{
			MethodName: "AddProvider",
			Handler:    _RatchetDaemon_AddProvider_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _RatchetDaemon_ListProviders_Handler,
		},
		{
			MethodName: "TestProvider",
			Handler:    _RatchetDaemon_TestProvider_Handler,
		},
		{
			MethodName: "RemoveProvider",
			Handler:    _RatchetDaemon_RemoveProvider_Handler,
		},
		{
			MethodName: "SetDefaultProvider",
			Handler:    _RatchetDaemon_SetDefaultProvider_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _RatchetDaemon_ListAgents_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _RatchetDaemon_GetAgentStatus_Handler,
		},
		{
			MethodName: "GetTeamStatus",
			Handler:    _RatchetDaemon_GetTeamStatus_Handler,
		},
		{
			MethodName: "RejectPlan",
			Handler:    _RatchetDaemon_RejectPlan_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RatchetDaemon_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _RatchetDaemon_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachSession",
			Handler:       _RatchetDaemon_AttachSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessage",
			Handler:       _RatchetDaemon_SendMessage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartTeam",
			Handler:       _RatchetDaemon_StartTeam_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ApprovePlan",
			Handler:       _RatchetDaemon_ApprovePlan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/ratchet.proto",
}
