// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/ratchet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // active, background, completed
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ActiveAgents  int32                  `protobuf:"varint,8,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Session) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Session) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

type CreateSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialPrompt string                 `protobuf:"bytes,1,opt,name=initial_prompt,json=initialPrompt,proto3" json:"initial_prompt,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionReq) Reset() {
	*x = CreateSessionReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionReq) ProtoMessage() {}

func (x *CreateSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionReq.ProtoReflect.Descriptor instead.
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionReq) GetInitialPrompt() string {
	if x != nil {
		return x.InitialPrompt
	}
	return ""
}

func (x *CreateSessionReq) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateSessionReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateSessionReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{3}
}

func (x *SessionList) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type AttachReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachReq) Reset() {
	*x = AttachReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachReq) ProtoMessage() {}

func (x *AttachReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachReq.ProtoReflect.Descriptor instead.
func (*AttachReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{4}
}

func (x *AttachReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DetachReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachReq) Reset() {
	*x = DetachReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachReq) ProtoMessage() {}

func (x *DetachReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachReq.ProtoReflect.Descriptor instead.
func (*DetachReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{5}
}

func (x *DetachReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillReq) Reset() {
	*x = KillReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillReq) ProtoMessage() {}

func (x *KillReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillReq.ProtoReflect.Descriptor instead.
func (*KillReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{6}
}

func (x *KillReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Chat streaming
type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_Token
	//	*ChatEvent_ToolStart
	//	*ChatEvent_ToolResult
	//	*ChatEvent_Permission
	//	*ChatEvent_AgentSpawned
	//	*ChatEvent_AgentMessage
	//	*ChatEvent_Complete
	//	*ChatEvent_Error
	//	*ChatEvent_History
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{8}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetToken() *TokenDelta {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *ChatEvent) GetToolStart() *ToolCallStart {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolStart); ok {
			return x.ToolStart
		}
	}
	return nil
}

func (x *ChatEvent) GetToolResult() *ToolCallResult {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ChatEvent) GetPermission() *PermissionRequest {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Permission); ok {
			return x.Permission
		}
	}
	return nil
}

func (x *ChatEvent) GetAgentSpawned() *AgentSpawned {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_AgentSpawned); ok {
			return x.AgentSpawned
		}
	}
	return nil
}

func (x *ChatEvent) GetAgentMessage() *AgentMessage {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_AgentMessage); ok {
			return x.AgentMessage
		}
	}
	return nil
}

func (x *ChatEvent) GetComplete() *SessionComplete {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ChatEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ChatEvent) GetHistory() *SessionHistory {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_History); ok {
			return x.History
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_Token struct {
	Token *TokenDelta `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type ChatEvent_ToolStart struct {
	ToolStart *ToolCallStart `protobuf:"bytes,2,opt,name=tool_start,json=toolStart,proto3,oneof"`
}

type ChatEvent_ToolResult struct {
	ToolResult *ToolCallResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ChatEvent_Permission struct {
	Permission *PermissionRequest `protobuf:"bytes,4,opt,name=permission,proto3,oneof"`
}

type ChatEvent_AgentSpawned struct {
	AgentSpawned *AgentSpawned `protobuf:"bytes,5,opt,name=agent_spawned,json=agentSpawned,proto3,oneof"`
}

type ChatEvent_AgentMessage struct {
	AgentMessage *AgentMessage `protobuf:"bytes,6,opt,name=agent_message,json=agentMessage,proto3,oneof"`
}

type ChatEvent_Complete struct {
	Complete *SessionComplete `protobuf:"bytes,7,opt,name=complete,proto3,oneof"`
}

type ChatEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type ChatEvent_History struct {
	History *SessionHistory `protobuf:"bytes,9,opt,name=history,proto3,oneof"`
}

func (*ChatEvent_Token) isChatEvent_Event() {}

func (*ChatEvent_ToolStart) isChatEvent_Event() {}

func (*ChatEvent_ToolResult) isChatEvent_Event() {}

func (*ChatEvent_Permission) isChatEvent_Event() {}

func (*ChatEvent_AgentSpawned) isChatEvent_Event() {}

func (*ChatEvent_AgentMessage) isChatEvent_Event() {}

func (*ChatEvent_Complete) isChatEvent_Event() {}

func (*ChatEvent_Error) isChatEvent_Event() {}

func (*ChatEvent_History) isChatEvent_Event() {}

type TokenDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDelta) Reset() {
	*x = TokenDelta{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDelta) ProtoMessage() {}

func (x *TokenDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDelta.ProtoReflect.Descriptor instead.
func (*TokenDelta) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{9}
}

func (x *TokenDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToolCallStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	CallId        string                 `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStart) Reset() {
	*x = ToolCallStart{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStart) ProtoMessage() {}

func (x *ToolCallStart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStart.ProtoReflect.Descriptor instead.
func (*ToolCallStart) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{10}
}

func (x *ToolCallStart) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallStart) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolCallStart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type ToolCallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResult) Reset() {
	*x = ToolCallResult{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResult) ProtoMessage() {}

func (x *ToolCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResult.ProtoReflect.Descriptor instead.
func (*ToolCallResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCallResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolCallResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PermissionRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PermissionRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *PermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // "once", "session", "always"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PermissionResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type AgentSpawned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSpawned) Reset() {
	*x = AgentSpawned{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpawned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpawned) ProtoMessage() {}

func (x *AgentSpawned) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpawned.ProtoReflect.Descriptor instead.
func (*AgentSpawned) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{14}
}

func (x *AgentSpawned) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSpawned) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentSpawned) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgent     string                 `protobuf:"bytes,1,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent       string                 `protobuf:"bytes,2,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{15}
}

func (x *AgentMessage) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *AgentMessage) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SessionComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionComplete) Reset() {
	*x = SessionComplete{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionComplete) ProtoMessage() {}

func (x *SessionComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionComplete.ProtoReflect.Descriptor instead.
func (*SessionComplete) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{16}
}

func (x *SessionComplete) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SessionComplete) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{17}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SessionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*HistoryMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHistory) Reset() {
	*x = SessionHistory{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHistory) ProtoMessage() {}

func (x *SessionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHistory.ProtoReflect.Descriptor instead.
func (*SessionHistory) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{18}
}

func (x *SessionHistory) GetMessages() []*HistoryMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type HistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, tool
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMessage) Reset() {
	*x = HistoryMessage{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMessage) ProtoMessage() {}

func (x *HistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMessage.ProtoReflect.Descriptor instead.
func (*HistoryMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{19}
}

func (x *HistoryMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HistoryMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HistoryMessage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *HistoryMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *HistoryMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Provider management
type AddProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // anthropic, openai, copilot, ollama, openrouter, cohere, custom
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderReq) Reset() {
	*x = AddProviderReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderReq) ProtoMessage() {}

func (x *AddProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderReq.ProtoReflect.Descriptor instead.
func (*AddProviderReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{20}
}

func (x *AddProviderReq) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *AddProviderReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddProviderReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AddProviderReq) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddProviderReq) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AddProviderReq) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AddProviderReq) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{21}
}

func (x *Provider) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Provider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Provider) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ProviderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderList) Reset() {
	*x = ProviderList{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderList) ProtoMessage() {}

func (x *ProviderList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderList.ProtoReflect.Descriptor instead.
func (*ProviderList) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{22}
}

func (x *ProviderList) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type TestProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderReq) Reset() {
	*x = TestProviderReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderReq) ProtoMessage() {}

func (x *TestProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderReq.ProtoReflect.Descriptor instead.
func (*TestProviderReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{23}
}

func (x *TestProviderReq) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type TestProviderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderResult) Reset() {
	*x = TestProviderResult{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderResult) ProtoMessage() {}

func (x *TestProviderResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderResult.ProtoReflect.Descriptor instead.
func (*TestProviderResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{24}
}

func (x *TestProviderResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestProviderResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestProviderResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type RemoveProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderReq) Reset() {
	*x = RemoveProviderReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderReq) ProtoMessage() {}

func (x *RemoveProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderReq.ProtoReflect.Descriptor instead.
func (*RemoveProviderReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveProviderReq) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type SetDefaultProviderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultProviderReq) Reset() {
	*x = SetDefaultProviderReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultProviderReq) ProtoMessage() {}

func (x *SetDefaultProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultProviderReq.ProtoReflect.Descriptor instead.
func (*SetDefaultProviderReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{26}
}

func (x *SetDefaultProviderReq) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// Agent management
type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	CurrentTask   string                 `protobuf:"bytes,7,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{27}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Agent) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *Agent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AgentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentList) Reset() {
	*x = AgentList{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentList) ProtoMessage() {}

func (x *AgentList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentList.ProtoReflect.Descriptor instead.
func (*AgentList) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{28}
}

func (x *AgentList) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusReq) Reset() {
	*x = AgentStatusReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusReq) ProtoMessage() {}

func (x *AgentStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusReq.ProtoReflect.Descriptor instead.
func (*AgentStatusReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{29}
}

func (x *AgentStatusReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Team management
type StartTeamReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Task                 string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrchestratorProvider string                 `protobuf:"bytes,3,opt,name=orchestrator_provider,json=orchestratorProvider,proto3" json:"orchestrator_provider,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartTeamReq) Reset() {
	*x = StartTeamReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTeamReq) ProtoMessage() {}

func (x *StartTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTeamReq.ProtoReflect.Descriptor instead.
func (*StartTeamReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{30}
}

func (x *StartTeamReq) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *StartTeamReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartTeamReq) GetOrchestratorProvider() string {
	if x != nil {
		return x.OrchestratorProvider
	}
	return ""
}

type TeamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*TeamEvent_AgentSpawned
	//	*TeamEvent_AgentMessage
	//	*TeamEvent_Token
	//	*TeamEvent_ToolStart
	//	*TeamEvent_ToolResult
	//	*TeamEvent_Permission
	//	*TeamEvent_Complete
	//	*TeamEvent_Error
	Event         isTeamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamEvent) Reset() {
	*x = TeamEvent{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEvent) ProtoMessage() {}

func (x *TeamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEvent.ProtoReflect.Descriptor instead.
func (*TeamEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{31}
}

func (x *TeamEvent) GetEvent() isTeamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TeamEvent) GetAgentSpawned() *AgentSpawned {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_AgentSpawned); ok {
			return x.AgentSpawned
		}
	}
	return nil
}

func (x *TeamEvent) GetAgentMessage() *AgentMessage {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_AgentMessage); ok {
			return x.AgentMessage
		}
	}
	return nil
}

func (x *TeamEvent) GetToken() *TokenDelta {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *TeamEvent) GetToolStart() *ToolCallStart {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_ToolStart); ok {
			return x.ToolStart
		}
	}
	return nil
}

func (x *TeamEvent) GetToolResult() *ToolCallResult {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *TeamEvent) GetPermission() *PermissionRequest {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_Permission); ok {
			return x.Permission
		}
	}
	return nil
}

func (x *TeamEvent) GetComplete() *SessionComplete {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *TeamEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*TeamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTeamEvent_Event interface {
	isTeamEvent_Event()
}

type TeamEvent_AgentSpawned struct {
	AgentSpawned *AgentSpawned `protobuf:"bytes,1,opt,name=agent_spawned,json=agentSpawned,proto3,oneof"`
}

type TeamEvent_AgentMessage struct {
	AgentMessage *AgentMessage `protobuf:"bytes,2,opt,name=agent_message,json=agentMessage,proto3,oneof"`
}

type TeamEvent_Token struct {
	Token *TokenDelta `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type TeamEvent_ToolStart struct {
	ToolStart *ToolCallStart `protobuf:"bytes,4,opt,name=tool_start,json=toolStart,proto3,oneof"`
}

type TeamEvent_ToolResult struct {
	ToolResult *ToolCallResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type TeamEvent_Permission struct {
	Permission *PermissionRequest `protobuf:"bytes,6,opt,name=permission,proto3,oneof"`
}

type TeamEvent_Complete struct {
	Complete *SessionComplete `protobuf:"bytes,7,opt,name=complete,proto3,oneof"`
}

type TeamEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

func (*TeamEvent_AgentSpawned) isTeamEvent_Event() {}

func (*TeamEvent_AgentMessage) isTeamEvent_Event() {}

func (*TeamEvent_Token) isTeamEvent_Event() {}

func (*TeamEvent_ToolStart) isTeamEvent_Event() {}

func (*TeamEvent_ToolResult) isTeamEvent_Event() {}

func (*TeamEvent_Permission) isTeamEvent_Event() {}

func (*TeamEvent_Complete) isTeamEvent_Event() {}

func (*TeamEvent_Error) isTeamEvent_Event() {}

type TeamStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamStatusReq) Reset() {
	*x = TeamStatusReq{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStatusReq) ProtoMessage() {}

func (x *TeamStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStatusReq.ProtoReflect.Descriptor instead.
func (*TeamStatusReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{32}
}

func (x *TeamStatusReq) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Agents        []*Agent               `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamStatus) Reset() {
	*x = TeamStatus{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStatus) ProtoMessage() {}

func (x *TeamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStatus.ProtoReflect.Descriptor instead.
func (*TeamStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{33}
}

func (x *TeamStatus) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamStatus) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TeamStatus) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *TeamStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Daemon health
type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	ActiveAgents   int32                  `protobuf:"varint,3,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	Uptime         string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_proto_ratchet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ratchet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ratchet_proto_rawDescGZIP(), []int{34}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthResponse) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

var File_internal_proto_ratchet_proto protoreflect.FileDescriptor

const file_internal_proto_ratchet_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/ratchet.proto\x12\aratchet\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xf8\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\ractive_agents\x18\b \x01(\x05R\factiveAgents\"\x8c\x01\n" +
	"\x10CreateSessionReq\x12%\n" +
	"\x0einitial_prompt\x18\x01 \x01(\tR\rinitialPrompt\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\";\n" +
	"\vSessionList\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.ratchet.SessionR\bsessions\"*\n" +
	"\tAttachReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"*\n" +
	"\tDetachReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"(\n" +
	"\aKillReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"I\n" +
	"\x0eSendMessageReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8a\x04\n" +
	"\tChatEvent\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x13.ratchet.TokenDeltaH\x00R\x05token\x127\n" +
	"\n" +
	"tool_start\x18\x02 \x01(\v2\x16.ratchet.ToolCallStartH\x00R\ttoolStart\x12:\n" +
	"\vtool_result\x18\x03 \x01(\v2\x17.ratchet.ToolCallResultH\x00R\n" +
	"toolResult\x12<\n" +
	"\n" +
	"permission\x18\x04 \x01(\v2\x1a.ratchet.PermissionRequestH\x00R\n" +
	"permission\x12<\n" +
	"\ragent_spawned\x18\x05 \x01(\v2\x15.ratchet.AgentSpawnedH\x00R\fagentSpawned\x12<\n" +
	"\ragent_message\x18\x06 \x01(\v2\x15.ratchet.AgentMessageH\x00R\fagentMessage\x126\n" +
	"\bcomplete\x18\a \x01(\v2\x18.ratchet.SessionCompleteH\x00R\bcomplete\x12+\n" +
	"\x05error\x18\b \x01(\v2\x13.ratchet.ErrorEventH\x00R\x05error\x123\n" +
	"\ahistory\x18\t \x01(\v2\x17.ratchet.SessionHistoryH\x00R\ahistoryB\a\n" +
	"\x05event\"&\n" +
	"\n" +
	"TokenDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"l\n" +
	"\rToolCallStart\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"d\n" +
	"\x0eToolCallResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x98\x01\n" +
	"\x11PermissionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"c\n" +
	"\x12PermissionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"\\\n" +
	"\fAgentSpawned\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"b\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x01 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x02 \x01(\tR\atoAgent\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"N\n" +
	"\x0fSessionComplete\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x05R\vtotalTokens\":\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"E\n" +
	"\x0eSessionHistory\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.ratchet.HistoryMessageR\bmessages\"\xb7\x01\n" +
	"\x0eHistoryMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc2\x01\n" +
	"\x0eAddProviderReq\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\"\x84\x01\n" +
	"\bProvider\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\"?\n" +
	"\fProviderList\x12/\n" +
	"\tproviders\x18\x01 \x03(\v2\x11.ratchet.ProviderR\tproviders\"'\n" +
	"\x0fTestProviderReq\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"g\n" +
	"\x12TestProviderResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\")\n" +
	"\x11RemoveProviderReq\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"-\n" +
	"\x15SetDefaultProviderReq\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\xcb\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12!\n" +
	"\fcurrent_task\x18\a \x01(\tR\vcurrentTask\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\"3\n" +
	"\tAgentList\x12&\n" +
	"\x06agents\x18\x01 \x03(\v2\x0e.ratchet.AgentR\x06agents\"+\n" +
	"\x0eAgentStatusReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"v\n" +
	"\fStartTeamReq\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x123\n" +
	"\x15orchestrator_provider\x18\x03 \x01(\tR\x14orchestratorProvider\"\xd5\x03\n" +
	"\tTeamEvent\x12<\n" +
	"\ragent_spawned\x18\x01 \x01(\v2\x15.ratchet.AgentSpawnedH\x00R\fagentSpawned\x12<\n" +
	"\ragent_message\x18\x02 \x01(\v2\x15.ratchet.AgentMessageH\x00R\fagentMessage\x12+\n" +
	"\x05token\x18\x03 \x01(\v2\x13.ratchet.TokenDeltaH\x00R\x05token\x127\n" +
	"\n" +
	"tool_start\x18\x04 \x01(\v2\x16.ratchet.ToolCallStartH\x00R\ttoolStart\x12:\n" +
	"\vtool_result\x18\x05 \x01(\v2\x17.ratchet.ToolCallResultH\x00R\n" +
	"toolResult\x12<\n" +
	"\n" +
	"permission\x18\x06 \x01(\v2\x1a.ratchet.PermissionRequestH\x00R\n" +
	"permission\x126\n" +
	"\bcomplete\x18\a \x01(\v2\x18.ratchet.SessionCompleteH\x00R\bcomplete\x12+\n" +
	"\x05error\x18\b \x01(\v2\x13.ratchet.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"(\n" +
	"\rTeamStatusReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"y\n" +
	"\n" +
	"TeamStatus\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12&\n" +
	"\x06agents\x18\x03 \x03(\v2\x0e.ratchet.AgentR\x06agents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x90\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12#\n" +
	"\ractive_agents\x18\x03 \x01(\x05R\factiveAgents\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime2\xa8\b\n" +
	"\rRatchetDaemon\x12<\n" +
	"\rCreateSession\x12\x19.ratchet.CreateSessionReq\x1a\x10.ratchet.Session\x124\n" +
	"\fListSessions\x12\x0e.ratchet.Empty\x1a\x14.ratchet.SessionList\x129\n" +
	"\rAttachSession\x12\x12.ratchet.AttachReq\x1a\x12.ratchet.ChatEvent0\x01\x123\n" +
	"\rDetachSession\x12\x12.ratchet.DetachReq\x1a\x0e.ratchet.Empty\x12/\n" +
	"\vKillSession\x12\x10.ratchet.KillReq\x1a\x0e.ratchet.Empty\x12<\n" +
	"\vSendMessage\x12\x17.ratchet.SendMessageReq\x1a\x12.ratchet.ChatEvent0\x01\x12B\n" +
	"\x13RespondToPermission\x12\x1b.ratchet.PermissionResponse\x1a\x0e.ratchet.Empty\x129\n" +
	"\vAddProvider\x12\x17.ratchet.AddProviderReq\x1a\x11.ratchet.Provider\x126\n" +
	"\rListProviders\x12\x0e.ratchet.Empty\x1a\x15.ratchet.ProviderList\x12E\n" +
	"\fTestProvider\x12\x18.ratchet.TestProviderReq\x1a\x1b.ratchet.TestProviderResult\x12<\n" +
	"\x0eRemoveProvider\x12\x1a.ratchet.RemoveProviderReq\x1a\x0e.ratchet.Empty\x12D\n" +
	"\x12SetDefaultProvider\x12\x1e.ratchet.SetDefaultProviderReq\x1a\x0e.ratchet.Empty\x120\n" +
	"\n" +
	"ListAgents\x12\x0e.ratchet.Empty\x1a\x12.ratchet.AgentList\x129\n" +
	"\x0eGetAgentStatus\x12\x17.ratchet.AgentStatusReq\x1a\x0e.ratchet.Agent\x128\n" +
	"\tStartTeam\x12\x15.ratchet.StartTeamReq\x1a\x12.ratchet.TeamEvent0\x01\x12<\n" +
	"\rGetTeamStatus\x12\x16.ratchet.TeamStatusReq\x1a\x13.ratchet.TeamStatus\x121\n" +
	"\x06Health\x12\x0e.ratchet.Empty\x1a\x17.ratchet.HealthResponse\x12*\n" +
	"\bShutdown\x12\x0e.ratchet.Empty\x1a\x0e.ratchet.EmptyB3Z1github.com/GoCodeAlone/ratchet-cli/internal/protob\x06proto3"

var (
	file_internal_proto_ratchet_proto_rawDescOnce sync.Once
	file_internal_proto_ratchet_proto_rawDescData []byte
)

func file_internal_proto_ratchet_proto_rawDescGZIP() []byte {
	file_internal_proto_ratchet_proto_rawDescOnce.Do(func() {
		file_internal_proto_ratchet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_ratchet_proto_rawDesc), len(file_internal_proto_ratchet_proto_rawDesc)))
	})
	return file_internal_proto_ratchet_proto_rawDescData
}

var file_internal_proto_ratchet_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_internal_proto_ratchet_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: ratchet.Empty
	(*Session)(nil),               // 1: ratchet.Session
	(*CreateSessionReq)(nil),      // 2: ratchet.CreateSessionReq
	(*SessionList)(nil),           // 3: ratchet.SessionList
	(*AttachReq)(nil),             // 4: ratchet.AttachReq
	(*DetachReq)(nil),             // 5: ratchet.DetachReq
	(*KillReq)(nil),               // 6: ratchet.KillReq
	(*SendMessageReq)(nil),        // 7: ratchet.SendMessageReq
	(*ChatEvent)(nil),             // 8: ratchet.ChatEvent
	(*TokenDelta)(nil),            // 9: ratchet.TokenDelta
	(*ToolCallStart)(nil),         // 10: ratchet.ToolCallStart
	(*ToolCallResult)(nil),        // 11: ratchet.ToolCallResult
	(*PermissionRequest)(nil),     // 12: ratchet.PermissionRequest
	(*PermissionResponse)(nil),    // 13: ratchet.PermissionResponse
	(*AgentSpawned)(nil),          // 14: ratchet.AgentSpawned
	(*AgentMessage)(nil),          // 15: ratchet.AgentMessage
	(*SessionComplete)(nil),       // 16: ratchet.SessionComplete
	(*ErrorEvent)(nil),            // 17: ratchet.ErrorEvent
	(*SessionHistory)(nil),        // 18: ratchet.SessionHistory
	(*HistoryMessage)(nil),        // 19: ratchet.HistoryMessage
	(*AddProviderReq)(nil),        // 20: ratchet.AddProviderReq
	(*Provider)(nil),              // 21: ratchet.Provider
	(*ProviderList)(nil),          // 22: ratchet.ProviderList
	(*TestProviderReq)(nil),       // 23: ratchet.TestProviderReq
	(*TestProviderResult)(nil),    // 24: ratchet.TestProviderResult
	(*RemoveProviderReq)(nil),     // 25: ratchet.RemoveProviderReq
	(*SetDefaultProviderReq)(nil), // 26: ratchet.SetDefaultProviderReq
	(*Agent)(nil),                 // 27: ratchet.Agent
	(*AgentList)(nil),             // 28: ratchet.AgentList
	(*AgentStatusReq)(nil),        // 29: ratchet.AgentStatusReq
	(*StartTeamReq)(nil),          // 30: ratchet.StartTeamReq
	(*TeamEvent)(nil),             // 31: ratchet.TeamEvent
	(*TeamStatusReq)(nil),         // 32: ratchet.TeamStatusReq
	(*TeamStatus)(nil),            // 33: ratchet.TeamStatus
	(*HealthResponse)(nil),        // 34: ratchet.HealthResponse
	(*timestamppb.Timestamp)(nil), // 35: google.protobuf.Timestamp
}
var file_internal_proto_ratchet_proto_depIdxs = []int32{
	35, // 0: ratchet.Session.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: ratchet.SessionList.sessions:type_name -> ratchet.Session
	9,  // 2: ratchet.ChatEvent.token:type_name -> ratchet.TokenDelta
	10, // 3: ratchet.ChatEvent.tool_start:type_name -> ratchet.ToolCallStart
	11, // 4: ratchet.ChatEvent.tool_result:type_name -> ratchet.ToolCallResult
	12, // 5: ratchet.ChatEvent.permission:type_name -> ratchet.PermissionRequest
	14, // 6: ratchet.ChatEvent.agent_spawned:type_name -> ratchet.AgentSpawned
	15, // 7: ratchet.ChatEvent.agent_message:type_name -> ratchet.AgentMessage
	16, // 8: ratchet.ChatEvent.complete:type_name -> ratchet.SessionComplete
	17, // 9: ratchet.ChatEvent.error:type_name -> ratchet.ErrorEvent
	18, // 10: ratchet.ChatEvent.history:type_name -> ratchet.SessionHistory
	19, // 11: ratchet.SessionHistory.messages:type_name -> ratchet.HistoryMessage
	35, // 12: ratchet.HistoryMessage.timestamp:type_name -> google.protobuf.Timestamp
	21, // 13: ratchet.ProviderList.providers:type_name -> ratchet.Provider
	27, // 14: ratchet.AgentList.agents:type_name -> ratchet.Agent
	14, // 15: ratchet.TeamEvent.agent_spawned:type_name -> ratchet.AgentSpawned
	15, // 16: ratchet.TeamEvent.agent_message:type_name -> ratchet.AgentMessage
	9,  // 17: ratchet.TeamEvent.token:type_name -> ratchet.TokenDelta
	10, // 18: ratchet.TeamEvent.tool_start:type_name -> ratchet.ToolCallStart
	11, // 19: ratchet.TeamEvent.tool_result:type_name -> ratchet.ToolCallResult
	12, // 20: ratchet.TeamEvent.permission:type_name -> ratchet.PermissionRequest
	16, // 21: ratchet.TeamEvent.complete:type_name -> ratchet.SessionComplete
	17, // 22: ratchet.TeamEvent.error:type_name -> ratchet.ErrorEvent
	27, // 23: ratchet.TeamStatus.agents:type_name -> ratchet.Agent
	2,  // 24: ratchet.RatchetDaemon.CreateSession:input_type -> ratchet.CreateSessionReq
	0,  // 25: ratchet.RatchetDaemon.ListSessions:input_type -> ratchet.Empty
	4,  // 26: ratchet.RatchetDaemon.AttachSession:input_type -> ratchet.AttachReq
	5,  // 27: ratchet.RatchetDaemon.DetachSession:input_type -> ratchet.DetachReq
	6,  // 28: ratchet.RatchetDaemon.KillSession:input_type -> ratchet.KillReq
	7,  // 29: ratchet.RatchetDaemon.SendMessage:input_type -> ratchet.SendMessageReq
	13, // 30: ratchet.RatchetDaemon.RespondToPermission:input_type -> ratchet.PermissionResponse
	20, // 31: ratchet.RatchetDaemon.AddProvider:input_type -> ratchet.AddProviderReq
	0,  // 32: ratchet.RatchetDaemon.ListProviders:input_type -> ratchet.Empty
	23, // 33: ratchet.RatchetDaemon.TestProvider:input_type -> ratchet.TestProviderReq
	25, // 34: ratchet.RatchetDaemon.RemoveProvider:input_type -> ratchet.RemoveProviderReq
	26, // 35: ratchet.RatchetDaemon.SetDefaultProvider:input_type -> ratchet.SetDefaultProviderReq
	0,  // 36: ratchet.RatchetDaemon.ListAgents:input_type -> ratchet.Empty
	29, // 37: ratchet.RatchetDaemon.GetAgentStatus:input_type -> ratchet.AgentStatusReq
	30, // 38: ratchet.RatchetDaemon.StartTeam:input_type -> ratchet.StartTeamReq
	32, // 39: ratchet.RatchetDaemon.GetTeamStatus:input_type -> ratchet.TeamStatusReq
	0,  // 40: ratchet.RatchetDaemon.Health:input_type -> ratchet.Empty
	0,  // 41: ratchet.RatchetDaemon.Shutdown:input_type -> ratchet.Empty
	1,  // 42: ratchet.RatchetDaemon.CreateSession:output_type -> ratchet.Session
	3,  // 43: ratchet.RatchetDaemon.ListSessions:output_type -> ratchet.SessionList
	8,  // 44: ratchet.RatchetDaemon.AttachSession:output_type -> ratchet.ChatEvent
	0,  // 45: ratchet.RatchetDaemon.DetachSession:output_type -> ratchet.Empty
	0,  // 46: ratchet.RatchetDaemon.KillSession:output_type -> ratchet.Empty
	8,  // 47: ratchet.RatchetDaemon.SendMessage:output_type -> ratchet.ChatEvent
	0,  // 48: ratchet.RatchetDaemon.RespondToPermission:output_type -> ratchet.Empty
	21, // 49: ratchet.RatchetDaemon.AddProvider:output_type -> ratchet.Provider
	22, // 50: ratchet.RatchetDaemon.ListProviders:output_type -> ratchet.ProviderList
	24, // 51: ratchet.RatchetDaemon.TestProvider:output_type -> ratchet.TestProviderResult
	0,  // 52: ratchet.RatchetDaemon.RemoveProvider:output_type -> ratchet.Empty
	0,  // 53: ratchet.RatchetDaemon.SetDefaultProvider:output_type -> ratchet.Empty
	28, // 54: ratchet.RatchetDaemon.ListAgents:output_type -> ratchet.AgentList
	27, // 55: ratchet.RatchetDaemon.GetAgentStatus:output_type -> ratchet.Agent
	31, // 56: ratchet.RatchetDaemon.StartTeam:output_type -> ratchet.TeamEvent
	33, // 57: ratchet.RatchetDaemon.GetTeamStatus:output_type -> ratchet.TeamStatus
	34, // 58: ratchet.RatchetDaemon.Health:output_type -> ratchet.HealthResponse
	0,  // 59: ratchet.RatchetDaemon.Shutdown:output_type -> ratchet.Empty
	42, // [42:60] is the sub-list for method output_type
	24, // [24:42] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_internal_proto_ratchet_proto_init() }
func file_internal_proto_ratchet_proto_init() {
	if File_internal_proto_ratchet_proto != nil {
		return
	}
	file_internal_proto_ratchet_proto_msgTypes[8].OneofWrappers = []any{
		(*ChatEvent_Token)(nil),
		(*ChatEvent_ToolStart)(nil),
		(*ChatEvent_ToolResult)(nil),
		(*ChatEvent_Permission)(nil),
		(*ChatEvent_AgentSpawned)(nil),
		(*ChatEvent_AgentMessage)(nil),
		(*ChatEvent_Complete)(nil),
		(*ChatEvent_Error)(nil),
		(*ChatEvent_History)(nil),
	}
	file_internal_proto_ratchet_proto_msgTypes[31].OneofWrappers = []any{
		(*TeamEvent_AgentSpawned)(nil),
		(*TeamEvent_AgentMessage)(nil),
		(*TeamEvent_Token)(nil),
		(*TeamEvent_ToolStart)(nil),
		(*TeamEvent_ToolResult)(nil),
		(*TeamEvent_Permission)(nil),
		(*TeamEvent_Complete)(nil),
		(*TeamEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_ratchet_proto_rawDesc), len(file_internal_proto_ratchet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_ratchet_proto_goTypes,
		DependencyIndexes: file_internal_proto_ratchet_proto_depIdxs,
		MessageInfos:      file_internal_proto_ratchet_proto_msgTypes,
	}.Build()
	File_internal_proto_ratchet_proto = out.File
	file_internal_proto_ratchet_proto_goTypes = nil
	file_internal_proto_ratchet_proto_depIdxs = nil
}
